Jose summer test2
markcmiller86/hello-numerical-world pull request #14
Opened 2024-06-12 19:41 UTC by Josee1031

2024-06-12 21:08 UTC, markcmiller86 commented
@Josee1031 it looks like you may have inadvertently included several files that should not be commited. All the `.o` files for example. Maybe a stray `git commit -a` was the cause (`-a` means all) or a `git add *`). Also, you included a results file from a run  `heat_results` drectory. Please remove those from the commit.

2024-06-12 22:30 UTC, markcmiller86 commented
@Josee1031 can you please cut-n-paste the actual warning text you were getting here?

2024-06-12 22:30 UTC, markcmiller86 commented
pinging @remontel here so he can follow along as needed.

2024-06-13 01:24 UTC, Josee1031 commented
> @Josee1031 can you please cut-n-paste the actual warning text you were getting here?

./Number.H:30:9: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
        sprintf(counts, "Adds:%d, Mults:%d, Divs:%d, Bytes:%d", Number::nadds, Number::nmults, Number::ndivs, (int) Number::nbytes);

2024-06-13 01:26 UTC, markcmiller86 commented
Hmmm...that looks like a *new* warning with your changes from `snprintf` to `sprintf`. It was using `snprintf` before. Can you revert your changes and produce the error message the code was originally emitting?

2024-06-13 01:39 UTC, Josee1031 commented
I was referring to the original bug. I fixed it on the original PR by changing it to snprintf and establishing a buffer size. The issue was that I pushed without using "make clean" and deleting the heat_results folder from the tutorial, that's why there were .o files and a heat_results folder. I made sure to remove them on the second PR.

2024-06-13 15:21 UTC, markcmiller86 requested changes
Ok, much better. Thanks for fixing this. I proposed a minor change to each line to keep space after comma styling. You can accept those by hitting the approprate button under the proposed change.

2024-06-13 15:21 UTC, markcmiller86 commented on Number.H
> +        snprintf(counts,sizeof(counts), "Adds:%d, Mults:%d, Divs:%d, Bytes:%d", Number::nadds, Number::nmults, Number::ndivs, (int) Number::nbytes);
```suggestion
        snprintf(counts, sizeof(counts), "Adds:%d, Mults:%d, Divs:%d, Bytes:%d", Number::nadds, Number::nmults, Number::ndivs, (int) Number::nbytes);
```

2024-06-13 15:21 UTC, markcmiller86 commented on args.C
> +    snprintf(fname,sizeof(fname), "%s/clargs.out", runame);
```suggestion
    snprintf(fname, sizeof(fname), "%s/clargs.out", runame);
```

2024-06-13 20:46 UTC, markcmiller86 approved these changes
Thank you

2024-06-13 20:47 UTC, merged